### ISSUE TITLE
Unable to activate chef-provisioning-docker-0.6

### ISSUE THREAD

**Issue by a13x212** [chef/chef-provisioning-docker#46]
Running into the following issue.

Unable to activate chef-provisioning-docker-0.6, because chef-provisioning-1.1.1 conflicts with chef-provisioning (~> 0.9)

**Comment by jeremiahsnapp** [comment]
@jkeiser it looks like the dependency in the gemspec file needs to be updated right?

https://github.com/chef/chef-provisioning-docker/blob/master/chef-provisioning-docker.gemspec#L16

**Comment by rmoriz** [comment]
duplicate of #45

**Comment by tyler-ball** [comment]
1.0 had some breaking API changes so we need to test chef-provisioning-docker with it before we get out a release.  In the mean time, you could use a local Gemfile to pin to the versions you want and use `bundle exec` to run your commands.

**Comment by ostraaten** [comment]
What version dependency changes should I make to make this work?

I removed `~> 0.9` changing dependency to  

```ruby
s.add_dependency 'chef-provisioning'
```
`bundle install` shows

```bash
[vagrant@localhost chef-provisioning-docker]$ bundle install
Resolving dependencies...
Using rake 10.3.2
...(lines deleted)
Using winrm 1.2.0
Using chef-provisioning 0.15.2 from https://github.com/opscode/chef-provisioning.git (at master)
Using excon 0.45.3
...(lines deleted)
Using chef-provisioning-docker 0.6 from source at .
...(lines deleted)
Using bundler 1.8.4
Bundle complete! 4 Gemfile dependencies, 61 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
[vagrant@localhost chef-provisioning-docker]$ 
```

But when I run the command in `README.md` it shows an error I don't understand

> ERROR: undefined method `cheffish' for nil:NilClass

Complete output in console is
```bash
[vagrant@localhost chef-provisioning-docker]$ CHEF_DRIVER=docker bundle exec chef-client -z docker_ubuntu_image.rb 
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/chef-12.0.3/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag
[2015-05-28T07:40:37+00:00] INFO: Started chef-zero at http://localhost:8889 with repository at /vagrant
  One version per cookbook

[2015-05-28T07:40:37+00:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.0.3
[2015-05-28T07:40:37+00:00] INFO: *** Chef 12.0.3 ***
[2015-05-28T07:40:37+00:00] INFO: Chef-client pid: 29883
[2015-05-28T07:40:41+00:00] INFO: Run List is []
[2015-05-28T07:40:41+00:00] INFO: Run List expands to []
[2015-05-28T07:40:41+00:00] INFO: Starting Chef Run for ostraaten

Running handlers:
[2015-05-28T07:40:41+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-05-28T07:40:41+00:00] ERROR: Exception handlers complete
[2015-05-28T07:40:41+00:00] FATAL: Stacktrace dumped to /vagrant/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 3.850152733 seconds
[2015-05-28T07:40:41+00:00] ERROR: undefined method `cheffish' for nil:NilClass
[2015-05-28T07:40:41+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[vagrant@localhost chef-provisioning-docker]$ 
```

**Comment by marc-** [comment]
I was watching for 1.0 compatibility issue for quite some time. At the moment following [line](https://github.com/chef/chef-provisioning/blob/master/lib/chef/provider/machine_image.rb#L76) in `chef-provisioning` breaks image creation, since destroying intermediate machine also invoke destroying underlying image we're trying to create ([see](https://github.com/chef/chef-provisioning-docker/blob/master/lib/chef/provisioning/docker_driver/driver.rb#L165) and this [issue](#37)). Should it be fixed in `chef-provisioning` or `chef-provisioning-docker`?
I think, we need to add flag into `machine` resource to prevent/enforce image deletion along with container.
At [ChefConf 2015](http://www.youtube.com/watch?v=LTTejR-5dIU) @jkeiser also was talking about significant improvements in image and container procedure for 1.0. Currently it is inefficient in terms of performance (you probably noticed that images are getting created really slow) and images size ([see](#26)).
Looking forward for `chef-provisioning-docker` 1.0 .

**Comment by marc-** [comment]
Made certain [adjustments](https://github.com/chef/chef-provisioning-docker/pull/47) to make it work with `chef-provisioning` >=1.0 .

**Comment by mwrock** [comment]
:+1: This driver is unusable with the last few DKs without forking with this revision

**Comment by randomcamel** [comment]
Fixed by PR #47. Needs a 0.7 release and to then get that sorted in DK.
